package html

import (
	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"
)

func HomePage2() Node {
	return page("Home2",
		Div(Class("flex h-screen bg-gray-100"),
			Div(Class("hidden md:flex flex-col w-64 bg-gray-800"),
				Div(Class("flex items-center justify-center h-16 bg-gray-900"),
					Span(Class("text-white font-bold uppercase"), Text("Sidebar")),
				),
				Div(Class("flex flex-col flex-1 overflow-y-auto"),
					Nav(Class("flex-1 px-2 py-4 bg-gray-800"),
						A(Href("#"), Class("flex items-center px-4 py-2 text-gray-100 hover:bg-gray-700"), Text("Dashboard"),
							SVG(Attr("xmlns", "http://www.w3.org/2000/svg"), Class("h-6 w-6 mr-2"), Attr("fill", "none"), Attr("viewBox", "0 0 24 24"), Attr("stroke", "currentColor"),
								El("path", Attr("stroke-linecap", "round"), Attr("stroke-linejoin", "round"), Attr("stroke-width", "2"), Attr("d", "M4 6h16M4 12h16M4 18h16")),
							),
						),
						A(Href("#"), Class("flex items-center px-4 py-2 mt-2 text-gray-100 hover:bg-gray-700"), Text("Messages"),
							SVG(Attr("xmlns", "http://www.w3.org/2000/svg"), Class("h-6 w-6 mr-2"), Attr("fill", "none"), Attr("viewBox", "0 0 24 24"), Attr("stroke", "currentColor"),
								El("path", Attr("stroke-linecap", "round"), Attr("stroke-linejoin", "round"), Attr("stroke-width", "2"), Attr("d", "M6 18L18 6M6 6l12 12")),
							),
						),
						A(Href("#"), Class("flex items-center px-4 py-2 mt-2 text-gray-100 hover:bg-gray-700"), Text("Settings"),
							SVG(Attr("xmlns", "http://www.w3.org/2000/svg"), Class("h-6 w-6 mr-2"), Attr("fill", "none"), Attr("viewBox", "0 0 24 24"), Attr("stroke", "currentColor"),
								El("path", Attr("stroke-linecap", "round"), Attr("stroke-linejoin", "round"), Attr("stroke-width", "2"), Attr("d", "M13 10V3L4 14h7v7l9-11h-7z")),
							),
						),
					),
				),
			),
			Div(Class("flex flex-col flex-1 overflow-y-auto"),
				Div(Class("flex items-center justify-between h-16 bg-white border-b border-gray-200"),
					Div(Class("flex items-center px-4"),
						Button(Class("text-gray-500 focus:outline-none focus:text-gray-700"),
							SVG(Attr("xmlns", "http://www.w3.org/2000/svg"), Class("h-6 w-6"), Attr("fill", "none"), Attr("viewBox", "0 0 24 24"), Attr("stroke", "currentColor"),
								El("path", Attr("stroke-linecap", "round"), Attr("stroke-linejoin", "round"), Attr("stroke-width", "2"), Attr("d", "M4 6h16M4 12h16M4 18h16")),
							),
						),
						Input(Class("mx-4 w-full border rounded-md px-4 py-2"), Type("text"), Placeholder("Search")),
					),
					Div(Class("flex items-center pr-4"),
						Button(Class("flex items-center text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700"),
							SVG(Attr("xmlns", "http://www.w3.org/2000/svg"), Class("h-6 w-6"), Attr("fill", "none"), Attr("viewBox", "0 0 24 24"), Attr("stroke", "currentColor"),
								El("path", Attr("stroke-linecap", "round"), Attr("stroke-linejoin", "round"), Attr("stroke-width", "2"), Attr("d", "M12 19l-7-7 7-7m5 14l7-7-7-7")),
							),
						),
					),
				),
				Div(Class("p-4"),
					H1(Class("text-2xl font-bold"), Text("Welcome to my dashboard!")),
					P(Class("mt-2 text-gray-600"), Text("This is an example dashboard using Tailwind CSS.")),
				),
			),
		),
	)
}
